### ISSUE TITLE
position: fixed 并不一定会触发新 layer

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Alexorz/animation-performance-guide#3]
Demo: http://jsbin.com/rohidayowi/edit?html,css,output

Env: Chrome Version 45.0.2454.101 (64-bit), Mac OSX, MacBook Air

Flags: All default

Source: https://codereview.chromium.org/1298493003/patch/140001/150021

**Comment by Alexorz** [comment]
确实，已经修改，感谢指正 : )
